# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5185c87b643605eccccf89ac153915f0f02b93c1a9dc1cb920208021e2befd360600ec0b613a4dc30987207db79c3fb8acca8f84e2502fac4f42ecca4faf7a7

test:
  secret_key_base: ed23de58d84a455fc4dd82a6f299bb7a0b7557a1e191a8f6fb69ab633e8e70b2215603d7d4d158e78f336816f716f63cf60ed6fe0a7ce61b2287e173111cbac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
